DROP DATABASE IF EXISTS movies CASCADE;

CREATE DATABASE IF NOT EXISTS movies;

USE movies;

CREATE TABLE Ratings
(UserID INT,
movieID INT,
rating INT,
TS INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '/t'
LINES TERMINATED BY '/n'
STORED AS TEXTFILE;

LOAD DATA LOCAL INPATH '/home/maria_dev/ratings.data'
INTO TABLE Ratings;

DESCRIBE Ratings;

SELECT rating, count(rating) AS TOTAL_OCCURENCES from Ratings 
GROUP BY rating
ORDER BY TOTAL_OCCURENCES DESC
